import fpgImage1 from '../../assets/fpg/fpg-01.jpg';  
import fpgImage2 from '../../assets/fpg/fpg-04.jpg';
import videoBg from "../../assets/Sierra/Sierra02.mp4";
import amazonia1 from "../../assets/Amazônia/06.jpg";
import amazonia2 from "../../assets/Amazônia/10.jpg";
import amazonia3 from "../../assets/Amazônia/Paris01.jpg";
import amazonia5 from "../../assets/Amazônia/11.jpg";
import amazonia6 from "../../assets/Amazônia/comp1.jpg";
import amazonia7 from "../../assets/Amazônia/12.png";
import amazonia8 from "../../assets/Amazônia/13.png";
import markela1 from "../../assets/Markela/aqua1.png";
import markela2 from "../../assets/Markela/aqua2.png";
import markela4 from "../../assets/Markela/ego1.png";
import markela5 from "../../assets/Markela/ego2.png";
import markela6 from "../../assets/Markela/perfume1.png";
import markela7 from "../../assets/Markela/sense1.png";
import markela8 from "../../assets/Markela/sense2.png";
import yamamura1 from "../../assets/yamamura.png";
import yamamura2 from "../../assets/Yamamura/Yamamura-revista.jpg";
import yamamuravideo1 from "../../assets/Yamamura/Yamamura.mp4"
import videoama from "../../assets/amawater.mp4";
import videoTalk1 from "../../assets/Talk/Chamada-08-10.mp4";

